n = input('digite algo:')
print('o tipo primitivo de {} é:'.format(n), type(n))
print('Só tem espaço?',n.isspace())
print('É um numero?',n.isnumeric())
print('é alfabetico?',n.isalpha())
print('é alfanumerico?',n.isalnum())
print('esta em maiusculas?',n.isupper())
print('esta em minuscula?',n.islower())
print('esta capitalizada?',n.istitle())
